### ISSUE TITLE
using `knitmd=FALSE` doesn't find md file in current directory

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/knit2synapse#10]
It seems something changed in knitr, so that the generated `md` file is not in the cache folder, but in the directory where the `Rmd` file is.

```
> knit2synapse::storeAndKnitToFileEntity(file="downloads.Rmd", parentId="syn4892835", knitmd = FALSE)
Error in knitfile2synapse(file = file, owner = owner, parentWikiId = parentWikiId,  : 
  markdown file downloads.md does not exist at this location: downloads_cache/downloads.md
```

**Comment by kdaily** [comment]
Ah. This only occurs if you use the built in `knit` function in RStudio (or otherwise use `knit`). If using `knit2synapse` then it stores the `md` in the cache dir.

**Comment by jaclynbeck-sage** [comment]
Closing, this appears to be working.
